name: Order collectors ci/cd

on:
  push:
    branches: [ "master" ]
    paths:
      - 'order_collector/**'
      - '.github/workflows/order_collector.yml'

  pull_request:
    branches: [ "master" ]
    paths:
      - 'order_collector/**'
      - '.github/workflows/order_collector.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com

      - name: Build the Docker image
        run: docker build  -t registry.heroku.com/coin-order-collector/coin-order-collector order_collector --build-arg BD_CONNECTION=${{ secrets.BD_CONNECTION }}

      - name: Push the Docker image
        run: docker push registry.heroku.com/coin-order-collector/coin-order-collector

      - name: Deploy app to heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release coin-dashboard-courses --app coin-order-collector

      - name: Scale heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku ps:scale coin-dashboard-courses=1 --app coin-dashboard-courses



